services:
  postgres:
    image: postgres:14-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Task@Manager2025
      - POSTGRES_USER=TaskManager
      - POSTGRES_DB=TaskManager
    networks:
      - localnet
  api: 
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=TaskManager;Username=TaskManager;Password=Task@Manager2025;Pooling=true;
    image: task-manager-api
    container_name: api
    ports:
      - 8080:8080
    build: ./src
    networks:
      - localnet
    depends_on:
      postgres:
        condition: service_healthy
  ui: 
    image: task-manager-ui
    container_name: ui
    ports:
      - 5000:5000
    build: ./src/TaskManager.Ui
    networks:
      - localnet
    depends_on:
      postgres:
        condition: service_healthy
networks:
  localnet:
    driver: bridge

volumes:
  pgdata: