services:
  postgres:
    image: postgres:14-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=eclipse@works2025
      - POSTGRES_USER=eclipseworks
      - POSTGRES_DB=eclipseworks
    networks:
      - localnet
  api: 
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=eclipseworks;Username=eclipseworks;Password=eclipse@works2025;Pooling=true;
    image: eclipse-api
    container_name: api
    ports:
      - 8080:8080
    build: ./src
    networks:
      - localnet
    depends_on:
      postgres:
        condition: service_healthy
networks:
  localnet:
    driver: bridge

volumes:
  pgdata: